# Generated by Django 4.2 on 2023-08-30 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog1", "0002_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
